# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:32
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_start', models.IntegerField()),
                ('span_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('description', models.TextField(null=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_start', models.IntegerField()),
                ('span_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionParticipantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('description', models.TextField(null=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treebank_id', models.IntegerField()),
                ('plain_form', models.TextField(null=True)),
                ('treebank_form', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='constructionparticipant',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.Sentence'),
        ),
        migrations.AddField(
            model_name='constructionparticipant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.ConstructionParticipantType'),
        ),
        migrations.AddField(
            model_name='constructioncategory',
            name='participants',
            field=models.ManyToManyField(to='constructions.ConstructionParticipantType'),
        ),
        migrations.AddField(
            model_name='construction',
            name='construction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.ConstructionCategory'),
        ),
        migrations.AddField(
            model_name='construction',
            name='participants',
            field=models.ManyToManyField(to='constructions.ConstructionParticipant'),
        ),
        migrations.AddField(
            model_name='construction',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.Sentence'),
        ),
    ]
