# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-02 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constructions', '0004_auto_20171202_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusfile',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
